## run_calibration { #run_calibration }

`run_calibration(self, calibration_points, infant_stims, shuffle=True, audio=None, focus_time=0.5, anim_type='zoom', save_calib=False)`

Run an infant-friendly calibration procedure with point selection and
animated stimuli. The calibration points are presented in a sequence
(either in order or shuffled) and at each point, an animated stimulus
is presented (either zooming or trilling). The procedure can optionally
play an attention-getting audio during the calibration process. The
calibration data can be saved to a file if desired.

### Parameters

| Name                 | Type                           | Description                                          | Default   |
|----------------------|--------------------------------|------------------------------------------------------|-----------|
| `calibration_points` | list of tuple                  | List of (x, y) coordinates for calibration points    | required  |
| `infant_stims`       | list of str                    | List of image file paths for calibration stimuli     | required  |
| `shuffle`            | bool, optional                 | Whether to shuffle stimuli order. Default is True    | `True`    |
| `audio`              | psychopy.sound.Sound, optional | Audio to play during calibration. Default is None    | `None`    |
| `focus_time`         | float, optional                | Time to wait before collecting data. Default is 0.5s | `0.5`     |
| `save_calib`         | bool, optional                 | Whether to save calibration data. Default is False   | `False`   |

### Returns

| Type   | Description                                     |
|--------|-------------------------------------------------|
| bool   | True if calibration successful, False otherwise |