# TobiiController.calibrate { #DeToX.TobiiController.calibrate }

```python
TobiiController.calibrate(
    calibration_points,
    infant_stims,
    shuffle=True,
    audio=None,
    focus_time=0.5,
    anim_type='zoom',
    save_calib=False,
)
```

Run an infant-friendly calibration procedure with point selection and
animated stimuli. The calibration points are presented in a sequence
(either in order or shuffled) and at each point, an animated stimulus
is presented (either zooming or trilling). The procedure can optionally
play an attention-getting audio during the calibration process. The
calibration data can be saved to a file if desired.

## Parameters {.doc-section .doc-section-parameters}

| Name               | Type                   | Description                                                                 | Default    |
|--------------------|------------------------|-----------------------------------------------------------------------------|------------|
| calibration_points | list of (float, float) | PsychoPy-normalized (x, y) coordinates for calibration targets.             | _required_ |
| infant_stims       | list of str            | List of image file paths for calibration stimuli.                           | _required_ |
| shuffle            | bool                   | Whether to shuffle stimuli order. Default is True.                          | `True`     |
| audio              | str                    | Path to audio file to play during calibration. Default is None.             | `None`     |
| focus_time         | float                  | Time to wait before collecting data. Default is 0.5s                        | `0.5`      |
| anim_type          | str                    | Type of animation to use. Options are 'zoom' or 'trill'. Default is 'zoom'. | `'zoom'`   |
| save_calib         | bool                   | Whether to save calibration data. Default is False                          | `False`    |

## Returns {.doc-section .doc-section-returns}

| Name   | Type   | Description                                     |
|--------|--------|-------------------------------------------------|
|        | bool   | True if calibration successful, False otherwise |