---
title: "Getting Started with DeToX"
description: "Starting using DeToX"
author: Tommaso Ghilardi

execute:
  enabled: false
---

In this tutorial we will take a look at the calibration procedure that usually precedes an eye-tracking experiment. In this tutoria we will cover two parts: 1. Centering the participant in the eye-tracker headbox 2. Running the calibration

## Centering the participant

This is not strictly part of the calibration but this is usually the first step when working with eye-trackers. Ok but what is this centering thing?? Well, eye-trackers have a limited area where they can track the eyes properly, this area is called the headbox. If the participant is outside this area the eye-tracker will not be able to track the eyes properly.

While we strive to always sit the aprticipants in teh same position adn at the same distance from teh screena dn eyetacker small diffrence can make lots of difference in terms of tracking quality.

Well...then how can we make sure to be as precise as possible?? Easy we can ask the tobii eyetracker to show us where the eyes of our participans are getting detected and then we can adjust their position until they are centered in the headbox.

Sounds simple in theory but it may even be easier in practice with DeToX!

::: callout-warning
We will assume you already followed the previous tutorial [Getting started](GettingStarted.qmd) so if you haven't check that please go and follow it!!
:::

Let's see how to do it:

### Setting up

```{python}
#| label: Libraries
#| eval: false
from psychopy import visual, core
from DeToX import ETracker


## Creat the window
win = visual.Window(
    size=[1920, 1080],  # Window dimensions in pixels
    fullscr=True,       # Expand to fill the entire screen
    units='pix'         # Use pixels as the measurement unit
)


## Connect to the eyetracker
ET_controller = ETracker(win)
```

Here we followed the previous tutorial and we just, imported the libraries, create a window where to render our stimuli and finally we connected to our eye-tracker.

Now we are ready to check if our participants in actually in our trackbox!

```{python}
Et_controller.show_status()


```