---
title: "Getting started"
description: "A Python wrapper around tobii_researcher and PsychoPy for easily running eye-tracking experiments with infants and toddlers."
author: Tommaso Ghilardi
---

This package was created out of the need to run eye-tracking experiments using `tobii_researcher`. The **Tobii SDK** provides a powerful way to interact with Tobii eye trackers in Python, offering many advanced features. However, certain aspects of its implementation can be complex and unintuitive.

<<<<<<< HEAD


=======
>>>>>>> 6672c1084872b41526f22b2c1208bc800d14d248
Since we often run experiments using **PsychoPy**, we developed this lightweight wrapper around **PsychoPy** and **`tobii_researcher`** to simplify the process. The goal is to make it easy to run **infant-friendly eye-tracking studies** while handling the more technical aspects of eye tracker integration.

This project didn’t start from scratch—it builds upon two existing packages that we have used in the past:

-   [**psychopy_tobii_infant**](https://github.com/yh-luo/psychopy_tobii_infant)

-   [**psychopy_tobii_controller**](https://github.com/hsogo/psychopy_tobii_controller)

While these packages already provided great solutions for integrating Tobii eye trackers with **PsychoPy**, we added a few extra features and improvements that we found useful for running **infant-friendly eye-tracking studies**. Our goal was to simplify some of the more technical aspects of eye tracker integration while keeping the flexibility needed for research.